package handyman.handymansection;

import handyman.usersection.userDashboardnew;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class HandymanManageRequest extends javax.swing.JFrame {
    
    Connection con;

    /**
     * Creates new form userDashboard
     */
    public HandymanManageRequest() {
        initComponents();
        String username = "root";
        String password = "2002";
        String dataConn = "jdbc:mysql://localhost:3306/handyman";
        try {
            con = DriverManager.getConnection(dataConn,username,password);
        } catch (Exception e) {
            System.out.println(e);
        }
     
        
    }
    PreparedStatement pst;
    PreparedStatement pstt;
    ResultSet rs1;
    /*public Connection getConnection(){
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 250));
        setMaximumSize(new java.awt.Dimension(630, 400));
        setMinimumSize(new java.awt.Dimension(630, 400));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Service No", "Service Info", "Customer Name", "Customer Place", "Service Status", "Assign Status", "Payment Status", "Total Payment (with extra)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 610, 270));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 641, 137, -1));

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 100, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 30));

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel1.setText("Service ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 30));

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel2.setText("Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 30));

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jLabel4.setText("MANAGE REQUEST");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, 20));

        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, 40));

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT sr.s_id,sr.s_problem,sr.s_customer,sr.s_location,sr.s_reqStatus,sr.s_paymentStatus,pr.p_totalpayment FROM service_records sr, payment_records pr where sr.s_id=pr.s_id";
        //String sql = "SELECT s_id,s_problem,s_location,s_reqStatus,s_paymentStatus FROM service_records";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {                
                model.addRow(new String[]{
                rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)
            });
            }            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT sr.s_id,sr.s_problem,sr.s_customer,sr.s_location,sr.s_reqStatus,sr.s_assignStatus,sr.s_paymentStatus,pr.p_totalpayment FROM service_records sr, payment_records pr where sr.s_id=pr.s_id";
        //String sql = "SELECT s_id,s_problem,s_location,s_reqStatus,s_paymentStatus FROM service_records";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {                
                model.addRow(new String[]{
                rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)
            });
            }            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            String serviceId = jTextField1.getText();
            String location = jTextField2.getText();
            String assignStatus = jTextField3.getText();
            /*
            model.setValueAt(serviceId,jTable1.getSelectedRow(),0);
            model.setValueAt(location,jTable1.getSelectedRow(),3);
            model.setValueAt(assignStatus,jTable1.getSelectedRow(),4);
            */
            try {
                
                String assignstatus = "Assigned";
                String handymanId = "10001";
                String sql = "UPDATE service_records set s_assignStatus='"+assignstatus+"' where s_id=?";
                String sql2 = "UPDATE payment_records set h_id='"+handymanId+"' where s_id=?";
                pst = con.prepareStatement(sql);
                pst.setString(1, serviceId);
                pstt = con.prepareStatement(sql2);
                pstt.setString(1, serviceId);
                pst.executeUpdate();
                pstt.executeUpdate();
                JOptionPane.showMessageDialog(this," Status: Assigned.\n Updated Successfully!!!");
                
            } catch (Exception e) {
            }
                
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //Select Data
        String serviceId = model.getValueAt(jTable1.getSelectedRow(),0).toString();
        String location = model.getValueAt(jTable1.getSelectedRow(),3).toString();
        String assignStatus = model.getValueAt(jTable1.getSelectedRow(),4).toString();
        
        //Set to TextFields
        jTextField1.setText(serviceId);
        jTextField2.setText(location);
        jTextField3.setText(assignStatus);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //========================================My Functions=======================================
    
    /*
    public void showTables(){
        
        try{
            int c;
            
            try{
        con = DriverManager.getConnection(dataConn, username, password);
        //pst = con.prepareStatement("Select s_id,s_problem_desc,s_cus_name,s_cus_loc,s_status,s_hours,s_finalpayment from service_tracker where s_handyman_role='Plumbing'");
        pst = con.prepareStatement("SELECT sr.s_id,sr.s_problem,ur.c_name,sr.s_location,sr.s_reqStatus,sr.s_paymentStatus,pr.p_totalpayment FROM service_records sr, payment_records pr, user_records ur");
        
        rs1 = pst.executeQuery();
                
                
                ResultSetMetaData rsd;
                rsd = (ResultSetMetaData) rs1.getMetaData();
                c = rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
                d.setRowCount(0);
                                
                
                
                while(rs1.next()){
                    Vector v2 = new Vector();
                    
                    for (int i=1;i<=c;i++){
                        v2.add(rs1.getString("s_id"));
                        v2.add(rs1.getString("s_problem"));
                        v2.add(rs1.getString("c_name"));
                        v2.add(rs1.getString("s_location"));
                        v2.add(rs1.getString("s_reqStatus"));
                        v2.add(rs1.getString("s_paymentStatus"));
                        v2.add(rs1.getString("p_totalpayment"));
                        //v2.add(rs.getString("s_fees"));
                                              
                    }
                    
                    d.addRow(v2);
                }
                
                
            } catch (Exception ex) {
                Logger.getLogger(userDashboardnew.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(userDashboardnew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    */
    
             
           
         
  
    //========================================My Functions=======================================
    
    
    
    //set Request fileds to empty
    /*private void clearFields(){
        //jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextArea1.setText(null);
    }
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HandymanManageRequest().setVisible(true);
                
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
