package handyman.usersection;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Userpayment extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "2002";
    private static final String dataConn = "jdbc:mysql://localhost:3306/handyman";

    /**
     * Creates new form userDashboard
     */
    public Userpayment() {
        initComponents();
        
    }

    Connection con=null;
    PreparedStatement pst;
    PreparedStatement pstt;
    ResultSet rs1;
    
    /*public Connection getConnection(){
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(220, 220));
        setMaximumSize(new java.awt.Dimension(620, 530));
        setMinimumSize(new java.awt.Dimension(620, 530));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel4.setText("Service Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 76, 130, 33));

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel5.setText("Problem");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 127, 130, 86));

        jTextField2.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 275, 210, 30));

        jButton6.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jButton6.setText("Get");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 78, 100, 30));

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel7.setText("Location");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 235, 130, 22));

        jButton5.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 113, 44));

        jTextField1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField1.setText("Service ID");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 77, 210, 30));

        jTextField4.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 231, 210, 30));

        jLabel8.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel8.setText("Service Hours");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 279, 130, 22));

        jTextField5.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 323, 210, 30));

        jLabel9.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel9.setText("Fees");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 323, 130, 26));

        jButton8.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jButton8.setText("Pay Now");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 113, 41));

        jLabel10.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel10.setText("Amount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 433, 130, 22));

        jTextField6.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 429, 210, 30));

        jTextField7.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 30));

        jLabel11.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel11.setText("Service Status");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 110, 22));

        jLabel16.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel16.setText("Extra Fees");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 375, 130, 22));

        jTextField8.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 371, 210, 30));

        jLabel17.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel17.setText("Pay Rupees");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 488, 130, 22));

        jTextField9.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 484, 210, 30));

        jLabel19.setFont(new java.awt.Font("Raleway", 1, 28)); // NOI18N
        jLabel19.setText("PAYMENT");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 127, 210, -1));

        jTextField10.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 130, 30));

        jLabel12.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel12.setText("Payment Status");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 110, 22));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //========================================My Functions=======================================
    
    public void upDateDB(){

        try{
            //String s_status = "Closed";
            //String final_payment = jTextField6.getText();
            
            String s_id = jTextField1.getText();
            con = DriverManager.getConnection(dataConn,username,password);
            String checkPayment = jTextField6.getText();
            String userPay = jTextField9.getText();
            String checkCondition;
            
            
        
            if(userPay.equals(checkPayment)){
                
                pst = con.prepareStatement("UPDATE payment_records set p_customerpayment='"+userPay+"' where s_id=?");
                pstt = con.prepareStatement("UPDATE service_records set s_reqStatus='Closed',s_paymentStatus='Completed' where s_id=?");
                pst.setString(1, s_id); 
                pstt.setString(1, s_id); 
                pst.executeUpdate();
                pstt.executeUpdate();
                      
                JOptionPane.showMessageDialog(this, "Payment Successful!!!");
                cleanFields();
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Invalid Payment!!!\n Try Again");

            }
                         
            //JOptionPane.showMessageDialog(this, "Registered Successfully!!!");
            
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    public void cleanFields(){
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextArea1.setText(null);
        jTextField4.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField5.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        
    }
   
    
    //Rounded Text Field Function
    public class RoundedJTextFiled extends JTextField{
        
        private Color backgroColor = Color.WHITE;
        
        protected void paintComponent(Graphics g){
            g.setColor(getBackground());
            g.fillRoundRect(0,0,getWidth()-1,getHeight()-1,15,15);
            super.paintComponent(g);
        }
        
    }
    
    //========================================My Functions=======================================
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        cleanFields();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/handyman","root", "2002");
            //pst = con.prepareStatement("select s_id,s_problem,s_reqStatus,serviceHours from service_records where s_id=? ");
            pst = con.prepareStatement("select sr.s_id,sr.s_problem,sr.s_location,sr.s_reqStatus,sr.s_paymentStatus,sr.serviceHours,pr.p_additionalcost,pr.p_totalpayment from service_records sr, payment_records pr where sr.s_id=? and pr.s_id=?");
           //Making Non Editable
           jTextField4.setEditable(false);
           jTextArea1.setEditable(false);
           jTextField2.setEditable(false);
           jTextField5.setEditable(false);
           jTextField7.setEditable(false);
           jTextField6.setEditable(false);
           jTextField8.setEditable(false);
           jTextField10.setEditable(false);
           
           //Pointing the Field
           jTextField1.requestFocus();
            String s_id = jTextField1.getText();
            pst.setString(1, s_id);
            pst.setString(2, s_id);
            rs1 = pst.executeQuery();
            
            
            if(rs1.next() == false){
                JOptionPane.showMessageDialog(this, "Service Id not found!!");
                jTextField1.setText(null);
                jTextField2.setText("");
                jTextArea1.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField7.setText("");
                jTextField6.setText("");
                jTextField8.setText("");
                jTextField10.setText("");
                jTextField1.requestFocus();
                }
                    
                else{
                        jTextArea1.setText(rs1.getString("s_problem"));
                        jTextField7.setText(rs1.getString("s_reqStatus"));
                        jTextField10.setText(rs1.getString("s_paymentStatus"));
                        jTextField4.setText(rs1.getString("s_location"));
                        jTextField2.setText(rs1.getString("serviceHours"));
                       // jTextField5.setText(rs1.getString("s_fees"));
                        jTextField8.setText(rs1.getString("p_additionalcost"));
                        jTextField6.setText(rs1.getString("p_totalpayment"));
                }
            /*else {
                JOptionPane.showMessageDialog(this, "Already Paid.\n Thank You!");
            }*/
            
        } catch (Exception ex) {
            Logger.getLogger(Userpayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 
        upDateDB();
        
     /*
        try {                                         
            
            
            String s_status = "Closed";
            String final_payment = jTextField6.getText();
            int s_id=0;String str_ids = Integer.toString(s_id);
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/handyman_db","ragesh", "root123");
            pst = con.prepareCall("UPDATE service_tracker set s_status='Closed', s_finalpayment='500' where s_id='189962' and s_status='Open'");
            //PreparedStatement ps = con.prepareCall("UPDATE service_tracker set s_status=?,s_finalpayment=? where s_id=?");
            pst.setString(1, s_status);
            pst.setString(2, final_payment);
            pst.setString(3, str_ids);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registered Successfully!!!");
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Userpayment.class.getName()).log(Level.SEVERE, null, ex);
        }
      

           
           */
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
                
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().equals("Service ID")){
            jTextField1.setText("");
            jTextField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
            jTextField1.setText("Service ID");
            jTextField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    //set Request fileds to empty
    /*private void clearFields(){
        //jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextArea1.setText(null);
    }
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userpayment().setVisible(true);
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
