package handyman.usersection;

import java.awt.Color;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class UsercreateService extends javax.swing.JFrame {

    private String uname;
    /**
     * Creates new form userDashboard
     */
    public UsercreateService() {
        initComponents();
    }
    
    public UsercreateService(String uname){
        initComponents();
        this.uname = uname;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 160));
        setMaximumSize(new java.awt.Dimension(610, 360));
        setMinimumSize(new java.awt.Dimension(610, 360));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel4.setText("Service Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, 22));

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel5.setText("Problem (Max 60 Characters)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 230, 48));

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel6.setText("Location");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 198, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 230, -1));

        jTextField2.setText("Location");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 222, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plumbing", "Electrical", "Painting", "Moving", "Cleaning", "Assembly", "General" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 160, -1));

        jButton6.setText("Create");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 100, 44));

        jTextField3.setText("Contact Number");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 222, -1));

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        jLabel7.setText("Contact Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 153, 22));

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 70, 40));

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jLabel1.setText("CREATE SERVICE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 100, 44));

        pack();
    }// </editor-fold>                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        new userDashboardnew().setVisible(true);
        setVisible(false);
    }                                        

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        try {
           

            //Generate Service id
            Random random = new Random();
            int randomnum = random.nextInt(99);
            String.format("%02d", randomnum);

            String servid = Integer.toString(randomnum);
            //jTextField1.setText(servid);
            String cus_location = jTextField2.getText();
            String cusnum = jTextField3.getText();
            String value = jComboBox1.getSelectedItem().toString();
            String problem_dec = jTextArea1.getText();
            String s_status = "Open";
            String s_assign = "Pending";
            String serv_hours = null;
            String fees = null; 
            String finalpayment = null; 
            String request_status = "Open";
            String assign_status = "Pending";
            String payment_status = "Pending";
            String customername = uname;
            
            if(cusnum.equals("") || problem_dec.equals("") || cus_location.equals("")){
                JOptionPane.showMessageDialog(this, "Kindly Fill the Details");
            }else{
                Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/handyman","root", "2002");
            //PreparedStatement ps = con.prepareCall("insert into service_tracker(s_id,s_cus_loc, s_cus_number,s_handyman_role, s_problem_desc,s_status,s_assign,s_hours,s_fees,s_finalpayment)values(?,?,?,?,?,?,?,?,?,?)");
            PreparedStatement ps = con.prepareCall("insert into service_records(s_id,s_type, s_problem, s_phone,s_location,s_reqStatus,s_assignStatus,s_paymentStatus,s_customer)values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, servid);
            ps.setString(2, value);
            ps.setString(3, problem_dec);
            ps.setString(4, cusnum);
            ps.setString(5, cus_location);
            ps.setString(6, request_status);
            ps.setString(7, assign_status);
            ps.setString(8, payment_status);
            ps.setString(9, customername);

            JOptionPane.showMessageDialog(this, "Service Id: "+servid+"\nRequest Registered Successfully!!!");
            
            PreparedStatement pst = con.prepareCall("insert into payment_records(s_id)values(?)");
            pst.setString(1, servid);

            
            ps.executeUpdate();
            pst.executeUpdate();
            clearFields();
            }
            

            

        } catch (Exception ex) {
            Logger.getLogger(UsercreateService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        if(jTextField3.getText().equals("Contact Number")){
            jTextField3.setText("");
            jTextField3.setForeground(new Color(0,0,0));
        }
    }                                       

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if(jTextField3.getText().equals("")){
            jTextField3.setText("Contact Number");
            jTextField3.setForeground(new Color(0,0,0));
        }
    }                                     

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        if(jTextField2.getText().equals("Location")){
            jTextField2.setText("");
            jTextField2.setForeground(new Color(0,0,0));
        }
    }                                       

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if(jTextField2.getText().equals("")){
            jTextField2.setText("Location");
            jTextField2.setForeground(new Color(0,0,0));
        }
    }                                     

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    //set Request fileds to empty
    private void clearFields(){
        //jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextArea1.setText(null);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsercreateService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
}
